In [ ]:

from google.colab import drive
import shutil, zipfile, os

# Mount Drive
drive.mount('/content/drive')

# Copy and extract ZIP
shutil.copy('/content/drive/MyDrive/data.zip', '/content/data.zip')
with zipfile.ZipFile('/content/data.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/')
os.remove('/content/data.zip')

# Verify
!ls /content/data

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
iml_malaria  malaria  miracle9to9


In [ ]:
# === SETUP: Get data from Google Drive ===

from google.colab import drive
import shutil
import zipfile
import os

# Step 1: Mount Google Drive
print("Mounting Google Drive...")
drive.mount('/content/drive')
print("✓ Drive mounted!\n")

# Step 2: Copy ZIP from Drive and extract
print("Copying and extracting data...")

# Path to your ZIP file in Google Drive
# CHANGE THIS to wherever you uploaded data.zip in your Drive
zip_path = '/content/drive/MyDrive/data.zip'

# Check if ZIP exists
if os.path.exists(zip_path):
    # Copy ZIP to Colab
    shutil.copy(zip_path, '/content/data.zip')

    # Extract
    with zipfile.ZipFile('/content/data.zip', 'r') as zip_ref:
        zip_ref.extractall('/content/')

    # Remove ZIP to save space
    os.remove('/content/data.zip')

    print("✓ Data extracted!\n")
else:
    print(f"❌ ZIP not found at {zip_path}")
    print("Please upload data.zip to your Google Drive first!")
    print("Or update zip_path to the correct location.")

# Step 3: Verify data structure
print("="*60)
print("VERIFYING DATA")
print("="*60)

if os.path.exists('/content/data'):
    for dataset in ['iml_malaria', 'malaria', 'miracle9to9']:
        dataset_path = f'/content/data/{dataset}'
        if os.path.exists(dataset_path):
            print(f"\n✓ {dataset} found")
            for split in ['train', 'val', 'test']:
                split_path = os.path.join(dataset_path, split)
                if os.path.exists(split_path):
                    classes = [c for c in os.listdir(split_path)
                              if os.path.isdir(os.path.join(split_path, c))]
                    print(f"  - {split}: {classes}")
        else:
            print(f"\n❌ {dataset} NOT found")
else:
    print("❌ /content/data folder not found!")

print("="*60)
print("\nIf everything shows ✓, you're ready to train!")

Mounting Google Drive...
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
✓ Drive mounted!

Copying and extracting data...
✓ Data extracted!

VERIFYING DATA

✓ iml_malaria found
  - train: ['trophozoite', 'schizont', 'ring', 'gametocyte']
  - val: ['trophozoite', 'schizont', 'ring', 'gametocyte']
  - test: ['trophozoite', 'schizont', 'ring', 'gametocyte']

✓ malaria found
  - train: ['trophozoite', 'schizont', 'ring', 'gametocyte']
  - val: ['trophozoite', 'schizont', 'ring', 'gametocyte']
  - test: ['trophozoite', 'schizont', 'ring', 'gametocyte']

✓ miracle9to9 found
  - train: ['Parasitized', 'Uninfected']
  - val: ['Parasitized', 'Uninfected']
  - test: ['Parasitized', 'Uninfected']

If everything shows ✓, you're ready to train!


In [ ]:
import os

# Quick verification
for dataset in ['iml_malaria', 'malaria', 'miracle9to9']:
    for split in ['train', 'val', 'test']:
        path = f'/content/data/{dataset}/{split}'
        if os.path.exists(path):
            classes = os.listdir(path)
            print(f"✓ {dataset}/{split}: {classes}")
        else:
            print(f"❌ MISSING: {dataset}/{split}")

✓ iml_malaria/train: ['trophozoite', 'schizont', '.DS_Store', 'ring', 'gametocyte']
✓ iml_malaria/val: ['trophozoite', 'schizont', 'ring', 'gametocyte']
✓ iml_malaria/test: ['trophozoite', 'schizont', 'ring', 'gametocyte']
✓ malaria/train: ['trophozoite', 'schizont', '.DS_Store', 'ring', 'gametocyte']
✓ malaria/val: ['trophozoite', 'schizont', '.DS_Store', 'ring', 'gametocyte']
✓ malaria/test: ['trophozoite', 'schizont', 'ring', 'gametocyte']
✓ miracle9to9/train: ['Parasitized', '.DS_Store', 'Uninfected']
✓ miracle9to9/val: ['Parasitized', '.DS_Store', 'Uninfected']
✓ miracle9to9/test: ['Parasitized', '.DS_Store', 'Uninfected']


In [ ]:
import os

# Check if data folder exists
if os.path.exists('/content/data'):
    print("✓ Data folder found!")

    # List all datasets
    for dataset in ['iml_malaria', 'malaria', 'miracle9to9']:
        dataset_path = f'/content/data/{dataset}'
        if os.path.exists(dataset_path):
            print(f"\n✓ {dataset} found")

            # Check for train/val/test folders
            for split in ['train', 'val', 'test']:
                split_path = os.path.join(dataset_path, split)
                if os.path.exists(split_path):
                    # Count classes
                    classes = os.listdir(split_path)
                    classes = [c for c in classes if os.path.isdir(os.path.join(split_path, c))]
                    print(f"  - {split}: {len(classes)} classes - {classes}")
                else:
                    print(f"  ✗ {split} folder missing!")
        else:
            print(f"✗ {dataset} NOT found at {dataset_path}")
else:
    print("✗ Data folder not found at /content/data")
    print("\nPlease upload your data or modify the path in STEP 1")

✓ Data folder found!

✓ iml_malaria found
  - train: 4 classes - ['trophozoite', 'schizont', 'ring', 'gametocyte']
  - val: 4 classes - ['trophozoite', 'schizont', 'ring', 'gametocyte']
  - test: 4 classes - ['trophozoite', 'schizont', 'ring', 'gametocyte']

✓ malaria found
  - train: 4 classes - ['trophozoite', 'schizont', 'ring', 'gametocyte']
  - val: 4 classes - ['trophozoite', 'schizont', 'ring', 'gametocyte']
  - test: 4 classes - ['trophozoite', 'schizont', 'ring', 'gametocyte']

✓ miracle9to9 found
  - train: 2 classes - ['Parasitized', 'Uninfected']
  - val: 2 classes - ['Parasitized', 'Uninfected']
  - test: 2 classes - ['Parasitized', 'Uninfected']


In [ ]:
!pip install tqdm scikit-learn


In [ ]:
import torch
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

# Define transforms
test_transforms = transforms.Compose([
    transforms.Resize((128, 128)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

# Try loading one dataset
try:
    test_dataset = datasets.ImageFolder(
        root='/content/data/iml_malaria/train',
        transform=test_transforms
    )

    test_loader = DataLoader(test_dataset, batch_size=4, shuffle=True)

    print(f"✓ Successfully loaded dataset!")
    print(f"  Classes: {test_dataset.classes}")
    print(f"  Number of images: {len(test_dataset)}")

    # Load one batch to verify
    images, labels = next(iter(test_loader))
    print(f"  Batch shape: {images.shape}")
    print(f"  Labels: {labels}")

except Exception as e:
    print(f"✗ Error loading dataset: {e}")
    print("\nCheck your folder structure and paths!")

✓ Successfully loaded dataset!
  Classes: ['gametocyte', 'ring', 'schizont', 'trophozoite']
  Number of images: 154
  Batch shape: torch.Size([4, 3, 128, 128])
  Labels: tensor([0, 0, 3, 1])


In [ ]:
from torchvision import models
import torch.nn as nn
import torch.optim as optim
from tqdm import tqdm

def quick_test_run():
    """Quick test with VGG-16 on iml_malaria for 2 epochs"""

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    # Load data
    train_transforms = transforms.Compose([
        transforms.Resize((128, 128)),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])

    train_dataset = datasets.ImageFolder('/content/data/iml_malaria/train', transform=train_transforms)
    val_dataset = datasets.ImageFolder('/content/data/iml_malaria/val', transform=test_transforms)

    train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=32, shuffle=False)

    num_classes = len(train_dataset.classes)
    print(f"Number of classes: {num_classes}")

    # Create model
    model = models.vgg16(weights=None)
    model.classifier[6] = nn.Linear(model.classifier[6].in_features, num_classes)
    model = model.to(device)

    # Setup training
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=0.001)

    # Train for 2 epochs
    for epoch in range(2):
        model.train()
        train_loss = 0

        for images, labels in tqdm(train_loader, desc=f"Epoch {epoch+1}"):
            images, labels = images.to(device), labels.to(device)

            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            train_loss += loss.item()

        # Validation
        model.eval()
        val_correct = 0
        val_total = 0

        with torch.no_grad():
            for images, labels in val_loader:
                images, labels = images.to(device), labels.to(device)
                outputs = model(images)
                _, predicted = torch.max(outputs, 1)
                val_correct += (predicted == labels).sum().item()
                val_total += labels.size(0)

        val_acc = 100 * val_correct / val_total
        print(f"Epoch {epoch+1}: Loss={train_loss/len(train_loader):.4f}, Val Acc={val_acc:.2f}%")

    print("\n✓ Test run completed successfully!")
    print("You're ready to run the full training script!")

# Run the test
quick_test_run()

Using device: cpu
Number of classes: 4


Epoch 1: 100%|██████████| 5/5 [02:16<00:00, 27.27s/it]


Epoch 1: Loss=104.2175, Val Acc=26.67%


Epoch 2: 100%|██████████| 5/5 [02:00<00:00, 24.20s/it]


Epoch 2: Loss=1.6139, Val Acc=26.67%

✓ Test run completed successfully!
You're ready to run the full training script!


In [ ]:
import torch
from torch import nn
import torch.optim as optim
from torch.utils.data import DataLoader
from torchvision import transforms, datasets, models
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_recall_fscore_support
import numpy as np
from tqdm import tqdm
import json
import os
from datetime import datetime

In [ ]:
#Configuration -Phase

# Device setup
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Base hyperparameters (same for all 9 baseline runs for fair comparison)
BASE_CONFIG = {
    'batch_size': 32,
    'learning_rate': 0.001,
    'num_epochs': 10,  # Adjust based on your time/resources
    'input_size': 128,  # All images resized to 128x128
    'optimizer': 'Adam',
    'loss_function': 'CrossEntropyLoss'
}

# Dataset paths - MODIFY THESE TO YOUR GOOGLE COLAB PATHS
DATASET_PATHS = {
    'iml_malaria': '/content/data/iml_malaria',     # Dataset A - 4 classes
    'malaria': '/content/data/malaria',              # Dataset B - 4 classes
    'miracle9to9': '/content/data/miracle9to9'       # Dataset C - 2 classes (binary)
}

# Results directory
RESULTS_DIR = '/content/results'
os.makedirs(RESULTS_DIR, exist_ok=True)


Using device: cpu


In [ ]:
#Setup paths for results

# Setup directories
# Change these paths to match your Google Drive structure
DATA_DIR = '/content/data'  # We'll copy data here from Drive
CHECKPOINT_DIR = '/content/drive/MyDrive/COMP472_Checkpoints'
RESULTS_DIR = '/content/drive/MyDrive/COMP472_Results'

# Create directories
os.makedirs(CHECKPOINT_DIR, exist_ok=True)
os.makedirs(RESULTS_DIR, exist_ok=True)

print(f"✓ Checkpoint directory: {CHECKPOINT_DIR}")
print(f"✓ Results directory: {RESULTS_DIR}")

✓ Checkpoint directory: /content/drive/MyDrive/COMP472_Checkpoints
✓ Results directory: /content/drive/MyDrive/COMP472_Results


In [ ]:
#Checking if all datasets are here

# Check if all datasets are present
datasets_to_check = ['iml_malaria', 'malaria', 'miracle9to9']

print("="*60)
print("VERIFYING DATA STRUCTURE")
print("="*60)

all_good = True
for dataset in datasets_to_check:
    dataset_path = f'/content/data/{dataset}'
    if os.path.exists(dataset_path):
        print(f"\n✓ {dataset} found")
        for split in ['train', 'val', 'test']:
            split_path = os.path.join(dataset_path, split)
            if os.path.exists(split_path):
                classes = [c for c in os.listdir(split_path)
                          if os.path.isdir(os.path.join(split_path, c))]
                num_images = sum([len(os.listdir(os.path.join(split_path, c)))
                                 for c in classes])
                print(f"  {split}: {len(classes)} classes, {num_images} images - {classes}")
            else:
                print(f"  ❌ {split} folder missing!")
                all_good = False
    else:
        print(f"\n❌ {dataset} NOT FOUND")
        all_good = False

print("="*60)
if all_good:
    print("✓ All datasets verified! Ready to train.")
else:
    print("❌ Some datasets missing. Fix this before proceeding!")

VERIFYING DATA STRUCTURE

✓ iml_malaria found
  train: 4 classes, 154 images - ['trophozoite', 'schizont', 'ring', 'gametocyte']
  val: 4 classes, 30 images - ['trophozoite', 'schizont', 'ring', 'gametocyte']
  test: 4 classes, 25 images - ['trophozoite', 'schizont', 'ring', 'gametocyte']

✓ malaria found
  train: 4 classes, 571 images - ['trophozoite', 'schizont', 'ring', 'gametocyte']
  val: 4 classes, 101 images - ['trophozoite', 'schizont', 'ring', 'gametocyte']
  test: 4 classes, 94 images - ['trophozoite', 'schizont', 'ring', 'gametocyte']

✓ miracle9to9 found
  train: 2 classes, 23426 images - ['Parasitized', 'Uninfected']
  val: 2 classes, 4134 images - ['Parasitized', 'Uninfected']
  test: 2 classes, 15832 images - ['Parasitized', 'Uninfected']
✓ All datasets verified! Ready to train.


In [ ]:
#Device setup

# Device setup
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"GPU Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")

# Base hyperparameters (SAME FOR ALL RUNS for fair comparison)
BASE_CONFIG = {
    'batch_size': 32,
    'learning_rate': 0.001,
    'num_epochs': 10,  # Adjust based on time
    'input_size': 128,
}

print(f"\nBase Configuration:")
for key, value in BASE_CONFIG.items():
    print(f"  {key}: {value}")

Using device: cpu

Base Configuration:
  batch_size: 32
  learning_rate: 0.001
  num_epochs: 10
  input_size: 128


In [ ]:
#Data transforms setup

# Training transforms (with augmentation)
train_transforms = transforms.Compose([
    transforms.Resize((BASE_CONFIG['input_size'], BASE_CONFIG['input_size'])),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomVerticalFlip(p=0.5),
    transforms.RandomRotation(degrees=20),
    transforms.ColorJitter(brightness=0.2, contrast=0.2),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

# Validation/Test transforms (no augmentation)
val_transforms = transforms.Compose([
    transforms.Resize((BASE_CONFIG['input_size'], BASE_CONFIG['input_size'])),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

print("✓ Data transforms defined")

✓ Data transforms defined


In [ ]:
#Model definition

def get_vgg16_model(num_classes):
    """VGG-16 model from scratch"""
    model = models.vgg16(weights=None)
    model.classifier[6] = nn.Linear(model.classifier[6].in_features, num_classes)
    return model

def get_mobilenet_v2_model(num_classes):
    """MobileNet-V2 model from scratch"""
    model = models.mobilenet_v2(weights=None)
    model.classifier[1] = nn.Linear(model.classifier[1].in_features, num_classes)
    return model

print("✓ Model definition functions ready")

✓ Model definition functions ready


In [ ]:
#Data loading

def load_dataset(dataset_name, batch_size=32):
    """Load train, val, test datasets"""

    dataset_path = f'/content/data/{dataset_name}'

    # Load datasets
    train_dataset = datasets.ImageFolder(
        root=os.path.join(dataset_path, 'train'),
        transform=train_transforms
    )

    val_dataset = datasets.ImageFolder(
        root=os.path.join(dataset_path, 'val'),
        transform=val_transforms
    )

    test_path = os.path.join(dataset_path, 'test')
    if os.path.exists(test_path):
        test_dataset = datasets.ImageFolder(root=test_path, transform=val_transforms)
    else:
        test_dataset = val_dataset
        print(f"⚠️ No test folder, using validation set")

    # Create loaders
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=2)
    val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, num_workers=2)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=2)

    num_classes = len(train_dataset.classes)
    class_names = train_dataset.classes

    print(f"\n{'='*60}")
    print(f"Dataset: {dataset_name}")
    print(f"Classes: {class_names}")
    print(f"Train: {len(train_dataset)} | Val: {len(val_dataset)} | Test: {len(test_dataset)}")
    print(f"{'='*60}\n")

    return train_loader, val_loader, test_loader, num_classes, class_names

print("✓ Data loading function ready")


✓ Data loading function ready


In [ ]:
#Training model

def train_model(model, train_loader, val_loader, config, run_name):
    """Train model with checkpoint saving to Google Drive"""

    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=config['learning_rate'])
    model.to(device)

    history = {
        'train_loss': [],
        'val_loss': [],
        'val_accuracy': [],
        'best_val_acc': 0.0,
        'best_epoch': 0
    }

    print(f"\n{'='*60}")
    print(f"Training: {run_name}")
    print(f"{'='*60}\n")

    for epoch in range(config['num_epochs']):
        # TRAINING
        model.train()
        running_loss = 0.0

        train_bar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{config['num_epochs']} [Train]")
        for images, labels in train_bar:
            images, labels = images.to(device), labels.to(device)

            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            running_loss += loss.item()
            train_bar.set_postfix({'loss': f"{loss.item():.4f}"})

        avg_train_loss = running_loss / len(train_loader)

        # VALIDATION
        model.eval()
        val_loss = 0.0
        val_correct = 0
        val_total = 0

        with torch.no_grad():
            for images, labels in tqdm(val_loader, desc=f"Epoch {epoch+1} [Val]", leave=False):
                images, labels = images.to(device), labels.to(device)
                outputs = model(images)
                loss = criterion(outputs, labels)

                val_loss += loss.item()
                _, predicted = torch.max(outputs, 1)
                val_correct += (predicted == labels).sum().item()
                val_total += labels.size(0)

        avg_val_loss = val_loss / len(val_loader)
        val_accuracy = 100.0 * val_correct / val_total

        # Update history
        history['train_loss'].append(avg_train_loss)
        history['val_loss'].append(avg_val_loss)
        history['val_accuracy'].append(val_accuracy)

        # Save checkpoint (to Google Drive!)
        checkpoint_path = os.path.join(CHECKPOINT_DIR, f"{run_name}_epoch{epoch+1}.pth")
        torch.save({
            'epoch': epoch + 1,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'val_accuracy': val_accuracy,
        }, checkpoint_path)

        # Save best model
        if val_accuracy > history['best_val_acc']:
            history['best_val_acc'] = val_accuracy
            history['best_epoch'] = epoch + 1
            best_path = os.path.join(CHECKPOINT_DIR, f"{run_name}_BEST.pth")
            torch.save({
                'epoch': epoch + 1,
                'model_state_dict': model.state_dict(),
                'val_accuracy': val_accuracy,
            }, best_path)

        print(f"Epoch {epoch+1}: Train Loss={avg_train_loss:.4f} | Val Acc={val_accuracy:.2f}% | Best={history['best_val_acc']:.2f}%")

    return model, history

print("✓ Training function ready")

✓ Training function ready


In [ ]:
#Evaluating

def evaluate_model(model, test_loader, class_names, run_name):
    """Evaluate model on test set"""

    model.eval()
    model.to(device)

    all_predictions = []
    all_labels = []

    print(f"\nEvaluating {run_name}...")

    with torch.no_grad():
        for images, labels in tqdm(test_loader, desc="Testing"):
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            _, predicted = torch.max(outputs, 1)

            all_predictions.extend(predicted.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    # Calculate metrics
    accuracy = accuracy_score(all_labels, all_predictions)
    precision, recall, f1, _ = precision_recall_fscore_support(
        all_labels, all_predictions, average='weighted', zero_division=0
    )

    cm = confusion_matrix(all_labels, all_predictions)
    report = classification_report(all_labels, all_predictions,
                                   target_names=class_names, zero_division=0)

    print(f"\n{'='*60}")
    print(f"Test Results - {run_name}")
    print(f"{'='*60}")
    print(f"Accuracy:  {accuracy*100:.2f}%")
    print(f"Precision: {precision:.4f}")
    print(f"Recall:    {recall:.4f}")
    print(f"F1-Score:  {f1:.4f}")
    print(f"\nConfusion Matrix:\n{cm}")
    print(f"{'='*60}\n")

    results = {
        'accuracy': float(accuracy),
        'precision': float(precision),
        'recall': float(recall),
        'f1_score': float(f1),
        'confusion_matrix': cm.tolist(),
    }

    return results

print("✓ Evaluation function ready")

✓ Evaluation function ready


In [ ]:
#Results logging

def log_results(run_name, dataset_name, model_name, run_type, config,
                history, test_results, class_names):
    """Save all results to JSON"""

    log_entry = {
        'run_name': run_name,
        'dataset_name': dataset_name,
        'model_name': model_name,
        'run_type': run_type,
        'timestamp': datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        'hyperparameters': config,
        'num_classes': len(class_names),
        'class_names': class_names,
        'best_val_accuracy': history['best_val_acc'],
        'best_epoch': history['best_epoch'],
        'test_accuracy': test_results['accuracy'] * 100,
        'test_precision': test_results['precision'],
        'test_recall': test_results['recall'],
        'test_f1_score': test_results['f1_score'],
        'confusion_matrix': test_results['confusion_matrix']
    }

    # Save to JSON in Google Drive
    log_path = os.path.join(RESULTS_DIR, f"{run_name}_results.json")
    with open(log_path, 'w') as f:
        json.dump(log_entry, f, indent=4)

    print(f"✓ Results saved to: {log_path}")

    return log_entry

print("✓ Logging function ready")

✓ Logging function ready


In [ ]:
#Testing on one dataset with 2 epochs

print("\n" + "="*60)
print("QUICK TEST RUN - VGG16 on iml_malaria (2 epochs)")
print("="*60 + "\n")

# Load data
train_loader, val_loader, test_loader, num_classes, class_names = load_dataset(
    'iml_malaria', BASE_CONFIG['batch_size']
)

# Create model
model = get_vgg16_model(num_classes)

# Quick config with only 2 epochs
test_config = BASE_CONFIG.copy()
test_config['num_epochs'] = 2

# Train
model, history = train_model(model, train_loader, val_loader, test_config, "TEST_VGG16_iml_malaria")

print("\n✓ Test run completed! If this worked, you're ready for full training.")



QUICK TEST RUN - VGG16 on iml_malaria (2 epochs)


Dataset: iml_malaria
Classes: ['gametocyte', 'ring', 'schizont', 'trophozoite']
Train: 154 | Val: 30 | Test: 25


Training: TEST_VGG16_iml_malaria



Epoch 1/2 [Train]: 100%|██████████| 5/5 [02:00<00:00, 24.05s/it, loss=1.3768]


Epoch 1: Train Loss=387.6828 | Val Acc=53.33% | Best=53.33%


Epoch 2/2 [Train]: 100%|██████████| 5/5 [02:21<00:00, 28.25s/it, loss=1.3498]


Epoch 2: Train Loss=2.2609 | Val Acc=26.67% | Best=53.33%

✓ Test run completed! If this worked, you're ready for full training.


In [ ]:
#Full training run 1 on VGG16 on iml_malaria

print("\n" + "="*60)
print("RUN 1/9: VGG16 on iml_malaria")
print("="*60 + "\n")

# Load data
train_loader, val_loader, test_loader, num_classes, class_names = load_dataset(
    'iml_malaria', BASE_CONFIG['batch_size']
)

# Create model
model = get_vgg16_model(num_classes)
run_name = "M4_VGG16_iml_malaria_scratch"

# Train
model, history = train_model(model, train_loader, val_loader, BASE_CONFIG, run_name)

# Load best checkpoint
best_checkpoint = torch.load(os.path.join(CHECKPOINT_DIR, f"{run_name}_BEST.pth"))
model.load_state_dict(best_checkpoint['model_state_dict'])

# Evaluate
test_results = evaluate_model(model, test_loader, class_names, run_name)

# Log
results_1 = log_results(run_name, 'iml_malaria', 'VGG16', 'scratch',
                       BASE_CONFIG, history, test_results, class_names)

print(f"\n✓✓ RUN 1 COMPLETE: Test Accuracy = {test_results['accuracy']*100:.2f}%")



RUN 1/9: VGG16 on iml_malaria


Dataset: iml_malaria
Classes: ['gametocyte', 'ring', 'schizont', 'trophozoite']
Train: 154 | Val: 30 | Test: 25


Training: M4_VGG16_iml_malaria_scratch



Epoch 1/10 [Train]: 100%|██████████| 5/5 [02:53<00:00, 34.74s/it, loss=1.7156]


Epoch 1: Train Loss=108.0532 | Val Acc=26.67% | Best=26.67%


Epoch 2/10 [Train]: 100%|██████████| 5/5 [02:27<00:00, 29.57s/it, loss=1.1903]


Epoch 2: Train Loss=1.3481 | Val Acc=26.67% | Best=26.67%


Epoch 3/10 [Train]: 100%|██████████| 5/5 [02:54<00:00, 34.93s/it, loss=1.2056]


Epoch 3: Train Loss=1.2753 | Val Acc=26.67% | Best=26.67%


Epoch 4/10 [Train]: 100%|██████████| 5/5 [02:35<00:00, 31.09s/it, loss=1.0894]


Epoch 4: Train Loss=1.1956 | Val Acc=53.33% | Best=53.33%


Epoch 5/10 [Train]: 100%|██████████| 5/5 [03:00<00:00, 36.20s/it, loss=1.1726]


Epoch 5: Train Loss=1.1753 | Val Acc=53.33% | Best=53.33%


Epoch 6/10 [Train]: 100%|██████████| 5/5 [02:39<00:00, 31.81s/it, loss=1.2254]


Epoch 6: Train Loss=1.1858 | Val Acc=53.33% | Best=53.33%


Epoch 7/10 [Train]: 100%|██████████| 5/5 [02:42<00:00, 32.44s/it, loss=1.2494]


Epoch 7: Train Loss=1.1707 | Val Acc=53.33% | Best=53.33%


Epoch 8/10 [Train]: 100%|██████████| 5/5 [02:48<00:00, 33.80s/it, loss=1.3203]


Epoch 8: Train Loss=1.1806 | Val Acc=53.33% | Best=53.33%


Epoch 9/10 [Train]: 100%|██████████| 5/5 [03:14<00:00, 38.95s/it, loss=1.1430]


Epoch 9: Train Loss=1.1539 | Val Acc=53.33% | Best=53.33%


Epoch 10/10 [Train]: 100%|██████████| 5/5 [02:48<00:00, 33.65s/it, loss=1.1452]


Epoch 10: Train Loss=1.1669 | Val Acc=53.33% | Best=53.33%

Evaluating M4_VGG16_iml_malaria_scratch...


Testing: 100%|██████████| 1/1 [00:06<00:00,  6.42s/it]



Test Results - M4_VGG16_iml_malaria_scratch
Accuracy:  52.00%
Precision: 0.2704
Recall:    0.5200
F1-Score:  0.3558

Confusion Matrix:
[[13  0  0  0]
 [ 7  0  0  0]
 [ 2  0  0  0]
 [ 3  0  0  0]]

✓ Results saved to: /content/drive/MyDrive/COMP472_Results/M4_VGG16_iml_malaria_scratch_results.json

✓✓ RUN 1 COMPLETE: Test Accuracy = 52.00%


In [ ]:
#VGG16 on malaria Run 2

print("\n" + "="*60)
print("RUN 2/9: VGG16 on malaria")
print("="*60 + "\n")

train_loader, val_loader, test_loader, num_classes, class_names = load_dataset(
    'malaria', BASE_CONFIG['batch_size']
)

model = get_vgg16_model(num_classes)
run_name = "M4_VGG16_malaria_scratch"

model, history = train_model(model, train_loader, val_loader, BASE_CONFIG, run_name)

best_checkpoint = torch.load(os.path.join(CHECKPOINT_DIR, f"{run_name}_BEST.pth"))
model.load_state_dict(best_checkpoint['model_state_dict'])

test_results = evaluate_model(model, test_loader, class_names, run_name)

results_2 = log_results(run_name, 'malaria', 'VGG16', 'scratch',
                       BASE_CONFIG, history, test_results, class_names)

print(f"\n✓✓ RUN 2 COMPLETE: Test Accuracy = {test_results['accuracy']*100:.2f}%")



RUN 2/9: VGG16 on malaria


Dataset: malaria
Classes: ['gametocyte', 'ring', 'schizont', 'trophozoite']
Train: 571 | Val: 101 | Test: 94


Training: M4_VGG16_malaria_scratch



Epoch 1/10 [Train]: 100%|██████████| 18/18 [08:33<00:00, 28.51s/it, loss=1.2059]


Epoch 1: Train Loss=44.6630 | Val Acc=63.37% | Best=63.37%


Epoch 2/10 [Train]: 100%|██████████| 18/18 [08:14<00:00, 27.45s/it, loss=1.2239]


Epoch 2: Train Loss=1.1784 | Val Acc=63.37% | Best=63.37%


Epoch 3/10 [Train]: 100%|██████████| 18/18 [08:46<00:00, 29.27s/it, loss=1.0292]


Epoch 3: Train Loss=1.1517 | Val Acc=63.37% | Best=63.37%


Epoch 4/10 [Train]: 100%|██████████| 18/18 [08:29<00:00, 28.28s/it, loss=1.2057]


Epoch 4: Train Loss=1.1460 | Val Acc=63.37% | Best=63.37%


Epoch 5/10 [Train]: 100%|██████████| 18/18 [08:18<00:00, 27.70s/it, loss=1.1005]


Epoch 5: Train Loss=1.1422 | Val Acc=63.37% | Best=63.37%


Epoch 6/10 [Train]: 100%|██████████| 18/18 [08:10<00:00, 27.23s/it, loss=1.2059]


Epoch 6: Train Loss=1.2123 | Val Acc=63.37% | Best=63.37%


Epoch 7/10 [Train]: 100%|██████████| 18/18 [08:54<00:00, 29.72s/it, loss=1.2117]


Epoch 7: Train Loss=1.2285 | Val Acc=63.37% | Best=63.37%


Epoch 8/10 [Train]: 100%|██████████| 18/18 [08:19<00:00, 27.76s/it, loss=1.2772]


Epoch 8: Train Loss=1.1598 | Val Acc=63.37% | Best=63.37%


Epoch 9/10 [Train]: 100%|██████████| 18/18 [08:22<00:00, 27.91s/it, loss=1.0820]


Epoch 9: Train Loss=1.1593 | Val Acc=63.37% | Best=63.37%


Epoch 10/10 [Train]: 100%|██████████| 18/18 [08:33<00:00, 28.54s/it, loss=1.3663]


Epoch 10: Train Loss=1.1507 | Val Acc=63.37% | Best=63.37%

Evaluating M4_VGG16_malaria_scratch...


Testing: 100%|██████████| 3/3 [00:36<00:00, 12.22s/it]



Test Results - M4_VGG16_malaria_scratch
Accuracy:  40.43%
Precision: 0.1634
Recall:    0.4043
F1-Score:  0.2328

Confusion Matrix:
[[ 0  0  0  3]
 [ 0  0  0 45]
 [ 0  0  0  8]
 [ 0  0  0 38]]

✓ Results saved to: /content/drive/MyDrive/COMP472_Results/M4_VGG16_malaria_scratch_results.json

✓✓ RUN 2 COMPLETE: Test Accuracy = 40.43%


In [ ]:
#VGG16 on miracle9to9 run 3

print("\n" + "="*60)
print("RUN 3/9: VGG16 on miracle9to9")
print("="*60 + "\n")

train_loader, val_loader, test_loader, num_classes, class_names = load_dataset(
    'miracle9to9', BASE_CONFIG['batch_size']
)

model = get_vgg16_model(num_classes)
run_name = "M4_VGG16_miracle9to9_scratch"

model, history = train_model(model, train_loader, val_loader, BASE_CONFIG, run_name)

best_checkpoint = torch.load(os.path.join(CHECKPOINT_DIR, f"{run_name}_BEST.pth"))
model.load_state_dict(best_checkpoint['model_state_dict'])

test_results = evaluate_model(model, test_loader, class_names, run_name)

results_3 = log_results(run_name, 'miracle9to9', 'VGG16', 'scratch',
                       BASE_CONFIG, history, test_results, class_names)

print(f"\n✓✓ RUN 3 COMPLETE: Test Accuracy = {test_results['accuracy']*100:.2f}%")



RUN 3/9: VGG16 on miracle9to9



NameError: name 'load_dataset' is not defined

In [ ]:
#MobileNetV2 on iml_malaria run 4

print("\n" + "="*60)
print("RUN 4/9: MobileNetV2 on iml_malaria")
print("="*60 + "\n")

train_loader, val_loader, test_loader, num_classes, class_names = load_dataset(
    'iml_malaria', BASE_CONFIG['batch_size']
)

model = get_mobilenet_v2_model(num_classes)
run_name = "M4_MobileNetV2_iml_malaria_scratch"

model, history = train_model(model, train_loader, val_loader, BASE_CONFIG, run_name)

best_checkpoint = torch.load(os.path.join(CHECKPOINT_DIR, f"{run_name}_BEST.pth"))
model.load_state_dict(best_checkpoint['model_state_dict'])

test_results = evaluate_model(model, test_loader, class_names, run_name)

results_4 = log_results(run_name, 'iml_malaria', 'MobileNetV2', 'scratch',
                       BASE_CONFIG, history, test_results, class_names)

print(f"\n✓✓ RUN 4 COMPLETE: Test Accuracy = {test_results['accuracy']*100:.2f}%")


In [ ]:
#MobileNetV2 on malaria run 5

print("\n" + "="*60)
print("RUN 5/9: MobileNetV2 on malaria")
print("="*60 + "\n")

train_loader, val_loader, test_loader, num_classes, class_names = load_dataset(
    'malaria', BASE_CONFIG['batch_size']
)

model = get_mobilenet_v2_model(num_classes)
run_name = "M4_MobileNetV2_malaria_scratch"

model, history = train_model(model, train_loader, val_loader, BASE_CONFIG, run_name)

best_checkpoint = torch.load(os.path.join(CHECKPOINT_DIR, f"{run_name}_BEST.pth"))
model.load_state_dict(best_checkpoint['model_state_dict'])

test_results = evaluate_model(model, test_loader, class_names, run_name)

results_5 = log_results(run_name, 'malaria', 'MobileNetV2', 'scratch',
                       BASE_CONFIG, history, test_results, class_names)

print(f"\n✓✓ RUN 5 COMPLETE: Test Accuracy = {test_results['accuracy']*100:.2f}%")


In [ ]:
#MobileNetV2 on miracle9to9 run 6

print("\n" + "="*60)
print("RUN 6/9: MobileNetV2 on miracle9to9")
print("="*60 + "\n")

train_loader, val_loader, test_loader, num_classes, class_names = load_dataset(
    'miracle9to9', BASE_CONFIG['batch_size']
)

model = get_mobilenet_v2_model(num_classes)
run_name = "M4_MobileNetV2_miracle9to9_scratch"

model, history = train_model(model, train_loader, val_loader, BASE_CONFIG, run_name)

best_checkpoint = torch.load(os.path.join(CHECKPOINT_DIR, f"{run_name}_BEST.pth"))
model.load_state_dict(best_checkpoint['model_state_dict'])

test_results = evaluate_model(model, test_loader, class_names, run_name)

results_6 = log_results(run_name, 'miracle9to9', 'MobileNetV2', 'scratch',
                       BASE_CONFIG, history, test_results, class_names)

print(f"\n✓✓ RUN 6 COMPLETE: Test Accuracy = {test_results['accuracy']*100:.2f}%")


In [ ]:
#Optimization process 1, run 7

print("\n" + "="*60)
print("OPTIMIZATION 1/3: VGG16 on iml_malaria with LR=0.0001")
print("="*60 + "\n")

train_loader, val_loader, test_loader, num_classes, class_names = load_dataset(
    'iml_malaria', BASE_CONFIG['batch_size']
)

model = get_vgg16_model(num_classes)
run_name = "M4_VGG16_iml_malaria_OPT_lr0.0001"

opt_config = BASE_CONFIG.copy()
opt_config['learning_rate'] = 0.0001

model, history = train_model(model, train_loader, val_loader, opt_config, run_name)

best_checkpoint = torch.load(os.path.join(CHECKPOINT_DIR, f"{run_name}_BEST.pth"))
model.load_state_dict(best_checkpoint['model_state_dict'])

test_results = evaluate_model(model, test_loader, class_names, run_name)

results_7 = log_results(run_name, 'iml_malaria', 'VGG16', 'optimization',
                       opt_config, history, test_results, class_names)

print(f"\n✓✓ OPT 1 COMPLETE: Test Accuracy = {test_results['accuracy']*100:.2f}%")


In [ ]:
#Optimization process 2, run 8

print("\n" + "="*60)
print("OPTIMIZATION 2/3: VGG16 on iml_malaria with LR=0.001 (baseline)")
print("="*60 + "\n")

train_loader, val_loader, test_loader, num_classes, class_names = load_dataset(
    'iml_malaria', BASE_CONFIG['batch_size']
)

model = get_vgg16_model(num_classes)
run_name = "M4_VGG16_iml_malaria_OPT_lr0.001"

opt_config = BASE_CONFIG.copy()
opt_config['learning_rate'] = 0.001

model, history = train_model(model, train_loader, val_loader, opt_config, run_name)

best_checkpoint = torch.load(os.path.join(CHECKPOINT_DIR, f"{run_name}_BEST.pth"))
model.load_state_dict(best_checkpoint['model_state_dict'])

test_results = evaluate_model(model, test_loader, class_names, run_name)

results_8 = log_results(run_name, 'iml_malaria', 'VGG16', 'optimization',
                       opt_config, history, test_results, class_names)

print(f"\n✓✓ OPT 2 COMPLETE: Test Accuracy = {test_results['accuracy']*100:.2f}%")


In [ ]:
#Optimization process 3, run 9

print("\n" + "="*60)
print("OPTIMIZATION 3/3: VGG16 on iml_malaria with LR=0.01")
print("="*60 + "\n")

train_loader, val_loader, test_loader, num_classes, class_names = load_dataset(
    'iml_malaria', BASE_CONFIG['batch_size']
)

model = get_vgg16_model(num_classes)
run_name = "M4_VGG16_iml_malaria_OPT_lr0.01"

opt_config = BASE_CONFIG.copy()
opt_config['learning_rate'] = 0.01

model, history = train_model(model, train_loader, val_loader, opt_config, run_name)

best_checkpoint = torch.load(os.path.join(CHECKPOINT_DIR, f"{run_name}_BEST.pth"))
model.load_state_dict(best_checkpoint['model_state_dict'])

test_results = evaluate_model(model, test_loader, class_names, run_name)

results_9 = log_results(run_name, 'iml_malaria', 'VGG16', 'optimization',
                       opt_config, history, test_results, class_names)

print(f"\n✓✓ OPT 3 COMPLETE: Test Accuracy = {test_results['accuracy']*100:.2f}%")


In [ ]:
#Testing summary


print("\n" + "="*80)
print("ALL TRAINING COMPLETE! MEMBER 4 WORKFLOW DONE!")
print("="*80)

# Collect all results
all_results = [results_1, results_2, results_3, results_4, results_5, results_6,
               results_7, results_8, results_9]

print(f"\nTotal runs: {len(all_results)}")
print("\nSummary:")
for i, result in enumerate(all_results, 1):
    print(f"{i}. {result['run_name']}: {result['test_accuracy']:.2f}%")

# Save master summary
summary_path = os.path.join(RESULTS_DIR, "member4_master_summary.json")
with open(summary_path, 'w') as f:
    json.dump(all_results, f, indent=4)

print(f"\n✓ Master summary saved: {summary_path}")
print(f"✓ All checkpoints in: {CHECKPOINT_DIR}")
print(f"✓ All results in: {RESULTS_DIR}")

print("\n" + "="*80)
print("Share these folders with Member 5 for evaluation!")
print("="*80)